image: mcr.microsoft.com/dotnet/framework/sdk:4.8


stages: 
    - build
    - test

before_script:
    - dotnet --version
    - cd VidamPark


build_mapModel:
    stage: build
    tags: [windows]
    script:
    - dotnet build MapModel


build_persistence:
    stage: build
    tags: [windows]
    script:
        - dotnet build Persistence
    dependencies:
        - build_mapModel

build_model:
    stage: build
    tags: [windows]
    script:
        - dotnet build Model
    dependencies:
        - build_persistence

build_view:
    stage: build
    tags: [windows]
    script:
        - dotnet build View
    dependencies:
        - build_model

build_app:
    stage: build
    tags: [windows]
    script:
        - dotnet build App
    dependencies:
        - build_view

#Test
test_model:
    stage: test
    tags: [windows]
    script:
        - dotnet build VidamParkTest
        - dotnet test VidamParkTest